### ISSUE TITLE
Get-CsUserId switch statement typo

### ISSUE THREAD

**Issue by StarkCaptain** [bk-cs/PSFalcon#13]
Line #26 - Typo, Id Needs to be Username 

'Id' { $Param.Uri = '/users/queries/user-uuids-by-email/v1?uid=' + $Username }

update to

'Username' { $Param.Uri = '/users/queries/user-uuids-by-email/v1?uid=' + $Username }

**Comment by bk-cs** [comment]
Thanks, StarkCaptain! 

This is now fixed in version 1.3.3, which has been pushed to GitHub and published in the PSGallery.
