### ISSUE TITLE
$Host check in Get-CsToken causes errors in editors like VSCode

### ISSUE THREAD

**Issue by mikeclemson** [bk-cs/PSFalcon#16]
https://github.com/bk-cs/PSFalcon/blob/1260cccbe1f17b6fb93f330d59b363fcb424baef/oauth2/Get-CsToken.psm1#L85-L91

Using $Host.Version.Major in Get-CsToken causes unexpected behavior because it is intended to check the version of the PowerShell engine, but $Host returns the version of the application hosting the PowerShell engine, not the engine itself. For example, $Host.Version when running Visual Studio Code returns Version 2020.4.0. Therefore, running PowerShell 5.1 in Visual Studio Code results in Get-CsToken failing because -AsPlainText is not a valid switch for ConvertFrom-SecureString in PowerShell 5.1.

https://adamtheautomator.com/check-powershell-version/

It would be better to use $PSVersionTable which is always the PowerShell engine version and won't change depending on whether PowerShell/PowerShell ISE is used or an editor like Visual Studio Code.

Also, it may not be valid in PowerShell 6 either, but I did not test:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-6

**Comment by Cephalowat** [comment]
Good catch.   `$PSVersionTable` works on pwsh 6+ too.

Nevertheless, the `SecureStringToBSTR` method works on both Powershell for Windows and Powershell core.. so perhaps the version check could be dropped altogether in this instance.

**Comment by bk-cs** [comment]
Merged. Thank you!

**Comment by Cephalowat** [comment]
> Also, it may not be valid in PowerShell 6 either, but I did not test:
> https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertfrom-securestring?view=powershell-6

I hadn't looked at this before writing previous pull request.  Indeed this is confirmed and Get-CSToken will always fail on PowerShell 6, line 86 needs to be changed to `$Host.Version.Major -gt 6`

**Comment by bk-cs** [comment]
Not sure what you mean by that comment -- Get-CsToken uses the 'ConvertFrom-SecureString' method when running PowerShell 6 or above, and the BSTR method when using PowerShell 5 or below.

**Comment by mikeclemson** [comment]
The documentation for ConvertFrom-SecureString for PowerShell 6 does not have an -AsPlainText parameter, which is definitely in PowerShell 7.

**Comment by bk-cs** [comment]
I changed the check to be '-ge 7' in v1.3.7 to fix the issue with PowerShell 6 and '-AsPlainText'. This might cause a problem with non-Windows devices running PowerShell 6 due to the lack of .NET (which the BSTR method uses).
