### ISSUE TITLE
Getting user, host name, and cs version.

### ISSUE THREAD

**Issue by wpline** [bk-cs/PSFalcon#24]
Sorry to inquire this in the issues section.  Is there a way to query for username, computer/host name, and crowdstrike agent version in one command?  Thanks.

**Comment by bk-cs** [comment]
No problem! I can also field questions like these on the [CrowdStrike subreddit](https://www.reddit.com/r/crowdstrike). :)

In the current version of PSFalcon, there is not one command that will do everything you're trying to do, but you can put two commands together in one line. Here's an example that will pull up to 5,000 hostnames and sensor versions (based on PSFalcon v1.4.1 defaults):

(Get-CsHostInfo -Id (Get-CsHostId).resources).resources | Select-Object hostname, agent_version

This does a few things, in the following order:

1. `(Get-CsHostId).resources` pulls the first 5,000 host identifiers
2. `(Get-CsHostInfo -Id ...).resources` retrieves the detail about those 5,000 host identifiers
3. `| Select-Object hostname, agent_version` keeps only the hostname and agent_version

Unfortunately, you can't pull "username" as that's a field that's not associated with a device, but rather an event. Username will show up in detections or incidents, for instance, but you won't find a username associated with a host directly.

You can get more complex and add in filters within the different steps, loop requests to retrieve more than 5,000 results, or save directly to a CSV file. For instance:

(Get-CsHostInfo -Id (Get-CsHostId -Filter "platform_name:'Windows'" -All).resources).resources | Select-Object hostname, agent_version | Export-Csv .\hosts.csv

Please let me know if you need any further clarification, either through this issue or on the subreddit. Thanks!
