### ISSUE TITLE
Update the parameter being used

### ISSUE THREAD

**Issue by jebanda-gh** [bk-cs/PSFalcon#25]
https://github.com/bk-cs/PSFalcon/blob/1583de780a3a3d2eae669aeec4f231e9dc4ec9b8/iocs/Get-CsIoc.psm1#L106
Lines 106 through 110 should have the parameters at the end of the line updated to use the key referenced at the beginning of the line. 

I've never been able to get the API call to work using the sources parameter, but I don't think it's an issue with the code. I think it's an issue with the API. I was referring to your code as a reference (which I often do when I can't get it to work on my own).

**Comment by bk-cs** [comment]
Hi jebanda-gh,

I'm not following the issue. Can you provide some code examples (errors, full URL requests, etc.)?

Thanks!

**Comment by jebanda-gh** [comment]
I'm saying that these lines should be updated from:
```
            'After' { $Param.Uri += '&from.expiration_timestamp=' + $Type }
            'Before' { $Param.Uri += '&to.expiration_timestamp=' + $Type }
            'Source' { $Param.Uri += '&sources=' + $Type }
            'CreatedBy' { $Param.Uri += '&created_by=' + $Type }
            'DeletedBy' { $Param.Uri += '&deleted_by=' + $Type }
```

to:
```
            'After' { $Param.Uri += '&from.expiration_timestamp=' + $After}
            'Before' { $Param.Uri += '&to.expiration_timestamp=' + $Before }
            'Source' { $Param.Uri += '&sources=' + $Source }
            'CreatedBy' { $Param.Uri += '&created_by=' + $CreatedBy }
            'DeletedBy' { $Param.Uri += '&deleted_by=' + $DeletedBy }
```

Note the end of each line.

**Comment by bk-cs** [comment]
Ah, thanks! This definitely should have been changed and I'm not sure how it was left like that. :)

I updated the command, updated the module to v1.4.2 and pushed the change to the PowerShell Gallery.

Thanks for creating this issue!
