### ISSUE TITLE
Get-CsHostId documentation missing hidden parameter

### ISSUE THREAD

**Issue by awesomecogs** [bk-cs/PSFalcon#27]
Good day.

First of all, thanks for this awesome module!  The work that's gone into it is greatly appreciated.

Within **PSFalcon/hosts/README.md**, the section for Get-CsHostId has no mention of the `-Hidden` parameter.

Thanks much!

**Comment by bk-cs** [comment]
Thank you! The switch has been added to the relevant README file.
