### ISSUE TITLE
Get-CsIoc Source Filter

### ISSUE THREAD

**Issue by jebanda-gh** [bk-cs/PSFalcon#28]
I'm just curious if you've been able to get the Get-CsIoc function to work while filtering by source. I get results when I use the source parameter, but they're not actually filtered.

**Comment by jebanda-gh** [comment]
I ended up getting this to work by changing 'sources' to 'source'. So, line 100 should read:
`'Source' { $Param.Uri += "&source=$Source" }`

**Comment by bk-cs** [comment]
Hi jebanda-gh! 

According to the API specification, "sources" is supposed to be the proper value. I tried changing it to 'source' and it doesn't appear to filter as I get all results back. Can you confirm?

My guess is that this filter doesn't actually work as advertised with the API, which is something outside of my control. PSFalcon is adding those values to the URI and making the request, but beyond grabbing what's documented and adding it to the module I can't really control the individual filters.

I recommend opening up a ticket with the CrowdStrike support team and let them know that the 'sources' filter doesn't appear to work when making calls to /indicators/queries/iocs/v1 (assuming using 'source' isn't actually working properly for you, as it wasn't for me).

**Comment by jebanda-gh** [comment]
Agreed. I thought it was working with 'source' instead of 'sources', but it
isn't.

I totally agree that this is not something you can control - just wanted to
make sure that it wasn't something that I was doing wrong.

I'll open a support case with CrowdStrike. Thanks!

**Comment by bk-cs** [comment]
No worries, I appreciate the attention to the issue! I wish it was something that would be as easy as renaming the field. :)
