### ISSUE TITLE
New-FXSample

### ISSUE THREAD

**Issue by bk-cs** [bk-cs/PSFalcon#4]
According to the [Swagger Documentation](https://assets.falcon.crowdstrike.com/support/api/swagger.html#/falconx-sandbox/UploadSampleV2), to submit a malware sample to Falcon X you have to use the equivalent of 'curl --data-binary' to submit a sample.

With Invoke-RestMethod, I was able to figure out the -Form parameter which works perfectly for other 'Add-' commands ([Add-RtrCloudScript](https://github.com/bk-cs/PSFalcon/blob/master/real-time-response/README.md), [Add-RtrCloudFile](https://github.com/bk-cs/PSFalcon/blob/master/real-time-response/README.md)), but those use the FormData field for submission, rather than Body.

Until someone can figure out how to convert a file to an octet stream and submit it in the Body field, I'm not sure how to get this one working. I'm grateful for any insight!

**Comment by soggysec** [comment]
The key is the `[]`s need to be provided to -Body. Example below: 

```
$fdata = Get-Content .\some_exe.exe
$headers = @{
  "authorization" = $falcon.token
  "accept" = "application/json"
}
$resp = invoke-restmethod -uri $uri -Method Post -headers $headers -ContentType 'application/octet-stream' -Body "[ $fdata ]"
```

**Comment by bk-cs** [comment]
Tested and working, thanks!
