### ISSUE TITLE
Response Object Handling

### ISSUE THREAD

**Issue by bk-cs** [bk-cs/PSFalcon#5]
@Cephalowat @soggysec 

Currently, when you run a command you'll receive a $PSObject response that contains all of the fields sent by the API (e.g. meta, resources, errors). This isn't very user friendly, requiring users to do things like (Get-CsHostId).resources if they only want the 'successful results'. 

I've toyed with the idea of outputting only the relevant fields, like resources if all results were successful, or errors if all the request failed, but that makes the [Invoke-FalconAPI](https://github.com/bk-cs/PSFalcon/blob/master/tools/Invoke-FalconAPI.psm1) command more complicated and raises the likelihood of bugs. 

I'd appreciate feedback on this issue as it will help direct development!

**Comment by bk-cs** [comment]
Also, I was considering that if I do start filtering to only 'successful results' or 'errors', having the -Verbose switch could always force full output, enabling easier logic when making scripts.

**Comment by Cephalowat** [comment]
> Also, I was considering that if I do start filtering to only 'successful results' or 'errors', having the '-Verbose' switch could always force full output, enabling easier logic when making scripts.

This sounds like a sane way to move forward and I like it a lot, but I would suggest not changing the behavior builtin parameters and name the switch `raw` or similar instead of `verbose`.

**Comment by soggysec** [comment]
I think we should have internal functions throw errors if the API call fails, that way we can handle it like normal PS commands. Wrap in a Try/Catch if it might fail, the response will be the data from the $_.errors attribute, and if success, we will provide the $_.resource instead.

**Comment by bk-cs** [comment]
This is a planned improvement for v2.0, currently in development.
