### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bk-cs** [bk-cs/PSFalcon#6]
@Cephalowat @soggysec

So far, @soggysec has suggested adding an 'Examples' section to the [main README](https://github.com/bk-cs/PSFalcon/blob/master/README.md) with a few commands.

I think tying those examples to 'use cases' would be helpful to illustrate to users how PSFalcon could be useful to them.

Possible Examples:
1. Find a Host Id and use Network Containment on the device
2. Find a Host Id and add that Host to a static Host Group
3. Find a Host Id, start a Real-time Response session and send a command

I appreciate all feedback in efforts to improve documentation. Thanks!

**Comment by bk-cs** [comment]
I added the first example (Network Containment)

**Comment by Cephalowat** [comment]
I'd be happy to add examples to main README and to assist extending documentation for the cmdlets themselves, but I think it would be best to resolve #5 first, to avoid having to go back and edit all the examples afterwards.  What do you think?

**Comment by bk-cs** [comment]
Added additional examples
