### ISSUE TITLE
Add array example to docs

### ISSUE THREAD

**Issue by jasonteplitz** [bk-cs/PSFalcon#7]
Array creation allows the tool to scale and it's really easy to do with input from a CSV file outputted from the CrowdStrike Host Management dashboard.  Export a CSV from the host management tab based on any filter you would like to use in conjunction with a PSFalcon command. Delete columns I-M in the CSV before conversion - these policy fields break the conversion.  API limitations may apply and require looping scripts.

Example Array Creation from CSV:

$ids = (Get-Content ./filename | ConvertFrom-Csv).‘Host ID’ 

Example Array Usage:

Contain an Array-

Start-CsContain -Id $ids  

Stop Containment on Array:
 
Stop-CsContain -Id $ids    

Please resist the temptation of containing your entire organization in a single execution

**Comment by bk-cs** [comment]
Complete
